### ISSUE TITLE
Add support for Unity 2020.1 and above

### ISSUE THREAD

**Issue by 253153** [OmiyaGames/omiya-games-embed-webgl-template#5]
Does this template work with Unity 2020.2?

**Comment by japtar10101** [comment]
Honestly, haven't tested it on Unity 2020.2 yet

**Comment by 253153** [comment]
I am having issues with WebGL on Unity 2020, and can't find a working template for it

**Comment by japtar10101** [comment]
OK, verified this *doesn't* work on Unity 2020.1.  They have changed the format of templates yet again, so I'll need to research what changes I have to make.

**Comment by japtar10101** [comment]
Started tackling this on a new debug Unity project here:
https://github.com/OmiyaGames/embed-webgl-template-debug-project

For personal note-taking reasons, here's the announcement Unity made in regards to changing how the WebGL now loads.
https://forum.unity.com/threads/changes-to-the-webgl-loader-and-templates-introduced-in-unity-2020-1.817698/

**Comment by japtar10101** [comment]
Fixed in e6bc8215fc90412e040366ef19b48cbea43b429e
